name: CI_Final

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  test:
    name: Test & Reports
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests and generate Allure report
        run: npm run ci:allure

      - name: Generate Playwright HTML report
        if: success() || failure()
        run: npx playwright show-report --output=playwright-report

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
